feat(ci): parse & publish cargo test results - enable sparse index for crates.io

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -15,6 +15,7 @@ on:
 
 env:
   CARGO_TERM_COLOR: always
+  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
 
 jobs:
   count_commits:
@@ -42,21 +43,34 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - uses: Swatinem/rust-cache@v2
-        with:
-          shared-key: "draco"
       - name: Build Release
         run: cargo +stable build --all --release
 
   test:
     name: Cargo Test
     runs-on: ubuntu-latest
-    needs: build 
+    needs: count_commits
+    if: ${{ needs.count_commits.outputs.count != '0' }}
     timeout-minutes: 30
     steps:
       - uses: actions/checkout@v3
       - uses: Swatinem/rust-cache@v2
+        cache-all-crates: "true"
+      - name: Setup Junitify
+        run: cargo install junitify
+      - name: Cargo Test
+        # RUSTC_BOOTSTRAP=1 is used to ensure unstable features are allowed in order to use unstable 
+        # json output and report times in tests. This is in preparation for rust 1.70 which will not 
+        # allow this anymore: 
+        # - https://github.com/rust-lang/rust/issues/75526
+        # - https://github.com/johnterickson/cargo2junit/issues/79
+        run: |
+          RUSTC_BOOTSTRAP=1 \
+          cargo +stable test --all -- \
+          --format=json -Z unstable-options --report-time \
+          | junitify -i --out test_results/
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
         with:
-          shared-key: "draco"
-          save-if: "false"
-      - name: Test
-        run: cargo +stable test --all
+          report_paths: 'test_results/*.xml'
